/* MLton g9a43e11 (built Sun Apr  5 22:29:53 NZST 2015 on xeon) */
/*   created this file on Sun Apr 05 23:03:38 2015. */
/* Do not edit this file. */
/* Flag settings:  */
/*    align: 8 */
/*    atMLtons: (16, @MLton, --) */
/*    chunk: chunk per function */
/*    closureConvertGlobalize: true */
/*    closureConvertShrink: true */
/*    codegen: amd64 */
/*    contifyIntoMain: false */
/*    debug: false */
/*    defaultChar: char8 */
/*    defaultWideChar: widechar32 */
/*    defaultInt: int32 */
/*    defaultReal: real64 */
/*    defaultWord: word32 */
/*    diag passes: [] */
/*    drop passes: [] */
/*    elaborate allowConstant (default): false */
/*    elaborate allowConstant (enabled): true */
/*    elaborate allowFFI (default): false */
/*    elaborate allowFFI (enabled): true */
/*    elaborate allowPrim (default): false */
/*    elaborate allowPrim (enabled): true */
/*    elaborate allowOverload (default): false */
/*    elaborate allowOverload (enabled): true */
/*    elaborate allowRebindEquals (default): false */
/*    elaborate allowRebindEquals (enabled): true */
/*    elaborate deadCode (default): false */
/*    elaborate deadCode (enabled): true */
/*    elaborate forceUsed (default): false */
/*    elaborate forceUsed (enabled): true */
/*    elaborate ffiStr (default):  */
/*    elaborate ffiStr (enabled): true */
/*    elaborate nonexhaustiveExnMatch (default): default */
/*    elaborate nonexhaustiveExnMatch (enabled): true */
/*    elaborate nonexhaustiveMatch (default): warn */
/*    elaborate nonexhaustiveMatch (enabled): true */
/*    elaborate redundantMatch (default): warn */
/*    elaborate redundantMatch (enabled): true */
/*    elaborate resolveScope (default): strdec */
/*    elaborate resolveScope (enabled): true */
/*    elaborate sequenceNonUnit (default): ignore */
/*    elaborate sequenceNonUnit (enabled): true */
/*    elaborate warnUnused (default): false */
/*    elaborate warnUnused (enabled): true */
/*    elaborate only: false */
/*    emit main: true */
/*    export header: None */
/*    exn history: false */
/*    generated output format: executable */
/*    gc check: Limit */
/*    indentation: 3 */
/*    inlineIntoMain: true */
/*    inlineLeafA: {loops = true, repeat = true, size = Some 20} */
/*    inlineLeafB: {loops = true, repeat = true, size = Some 40} */
/*    inlineNonRec: {small = 60, product = 320} */
/*    input file: 16 */
/*    keep CoreML: false */
/*    keep def use: true */
/*    keep dot: false */
/*    keep Machine: false */
/*    keep passes: [] */
/*    keep RSSA: false */
/*    keep SSA: false */
/*    keep SSA2: false */
/*    keep SXML: false */
/*    keep XML: false */
/*    extra_: false */
/*    lib dir: /home/a/Projects/mlton/build/lib */
/*    lib target dir: /home/a/Projects/mlton/build/lib/targets/unknown */
/*    loop passes: 1 */
/*    mark cards: true */
/*    max function size: 10000 */
/*    mlb path vars: [{var = MLTON_ROOT, path = $(LIB_MLTON_DIR)/sml}, {var = SML_LIB, path = $(LIB_MLTON_DIR)/sml}] */
/*    native commented: 0 */
/*    native live stack: false */
/*    native optimize: 1 */
/*    native move hoist: true */
/*    native copy prop: true */
/*    native copy prop cutoff: 1000 */
/*    native cutoff: 100 */
/*    native live transfer: 8 */
/*    native shuffle: true */
/*    native ieee fp: false */
/*    native split: Some 20000 */
/*    optimizationPasses: [<ssa2::default>, <ssa::default>, <sxml::default>, <xml::default>] */
/*    polyvariance: Some {hofo = true, rounds = 2, small = 30, product = 300} */
/*    prefer abs paths: false */
/*    prof passes: [] */
/*    profile: None */
/*    profile branch: false */
/*    profile C: [] */
/*    profile IL: ProfileSource */
/*    profile include/exclude: [(Seq [Star [.], Or [Seq [Seq [[$], [(], [S], [M], [L], [_], [L], [I], [B], [)]]]], Star [.]], false)] */
/*    profile raise: false */
/*    profile stack: false */
/*    profile val: false */
/*    show basis: None */
/*    show def-use: None */
/*    show types: true */
/*    target: unknown */
/*    target arch: AMD64 */
/*    target OS: OpenBSD */
/*    type check: true */
/*    verbosity: Silent */
/*    warn unrecognized annotation: true */
/*    warn deprecated features: true */
/*    zone cut depth: 100 */
#define _ISOC99_SOURCE
#include <amd64-main.h>

PRIVATE struct GC_state gcState;
PRIVATE CPointer globalCPointer [0];
PRIVATE CPointer CReturnQ;
PRIVATE Int8 globalInt8 [0];
PRIVATE Int8 CReturnI8;
PRIVATE Int16 globalInt16 [0];
PRIVATE Int16 CReturnI16;
PRIVATE Int32 globalInt32 [0];
PRIVATE Int32 CReturnI32;
PRIVATE Int64 globalInt64 [0];
PRIVATE Int64 CReturnI64;
PRIVATE Objptr globalObjptr [269];
PRIVATE Objptr CReturnP;
PRIVATE Real32 globalReal32 [0];
PRIVATE Real32 CReturnR32;
PRIVATE Real64 globalReal64 [0];
PRIVATE Real64 CReturnR64;
PRIVATE Word8 globalWord8 [0];
PRIVATE Word8 CReturnW8;
PRIVATE Word16 globalWord16 [0];
PRIVATE Word16 CReturnW16;
PRIVATE Word32 globalWord32 [2];
PRIVATE Word32 CReturnW32;
PRIVATE Word64 globalWord64 [1];
PRIVATE Word64 CReturnW64;
PRIVATE Pointer globalObjptrNonRoot [1];
PRIVATE Pointer MLton_FFI_opArgsResPtr;
static int saveGlobals (FILE *f) {
	SaveArray (globalCPointer, f);
	SaveArray (globalInt8, f);
	SaveArray (globalInt16, f);
	SaveArray (globalInt32, f);
	SaveArray (globalInt64, f);
	SaveArray (globalObjptr, f);
	SaveArray (globalReal32, f);
	SaveArray (globalReal64, f);
	SaveArray (globalWord8, f);
	SaveArray (globalWord16, f);
	SaveArray (globalWord32, f);
	SaveArray (globalWord64, f);
	return 0;
}
static int loadGlobals (FILE *f) {
	LoadArray (globalCPointer, f);
	LoadArray (globalInt8, f);
	LoadArray (globalInt16, f);
	LoadArray (globalInt32, f);
	LoadArray (globalInt64, f);
	LoadArray (globalObjptr, f);
	LoadArray (globalReal32, f);
	LoadArray (globalReal64, f);
	LoadArray (globalWord8, f);
	LoadArray (globalWord16, f);
	LoadArray (globalWord32, f);
	LoadArray (globalWord64, f);
	return 0;
}
BeginIntInfInits
EndIntInfInits
BeginVectorInits
VectorInitElem ("busy", 1, 169, 4)
VectorInitElem ("Thread.atomicEnd", 1, 234, 16)
VectorInitElem ("mlink", 1, 193, 5)
VectorInitElem ("inval", 1, 187, 5)
VectorInitElem ("txtbsy", 1, 230, 6)
VectorInitElem ("noexec", 1, 203, 6)
VectorInitElem ("netreset", 1, 197, 8)
VectorInitElem ("hostunreach", 1, 182, 11)
VectorInitElem ("rofs", 1, 224, 4)
VectorInitElem ("netdown", 1, 196, 7)
VectorInitElem ("\" failed with ", 1, 260, 14)
VectorInitElem ("pipe", 1, 220, 4)
VectorInitElem ("flushOut", 1, 258, 8)
VectorInitElem ("connreset", 1, 174, 9)
VectorInitElem ("nobufs", 1, 200, 6)
VectorInitElem ("stale", 1, 227, 5)
VectorInitElem ("unhandled exception: ", 1, 242, 21)
VectorInitElem ("<stdout>", 1, 252, 8)
VectorInitElem ("Sequence.length", 1, 236, 15)
VectorInitElem ("<UNKNOWN>", 1, 264, 9)
VectorInitElem ("noent", 1, 202, 5)
VectorInitElem ("SysErr", 1, 246, 6)
VectorInitElem ("dquot", 1, 178, 5)
VectorInitElem ("nosys", 1, 209, 5)
VectorInitElem ("mfile", 1, 192, 5)
VectorInitElem ("again", 1, 166, 5)
VectorInitElem ("isconn", 1, 189, 6)
VectorInitElem ("Io", 1, 247, 2)
VectorInitElem ("dom", 1, 177, 3)
VectorInitElem ("Fail", 1, 245, 4)
VectorInitElem ("range", 1, 223, 5)
VectorInitElem ("toobig", 1, 229, 6)
VectorInitElem ("io", 1, 188, 2)
VectorInitElem ("connaborted", 1, 172, 11)
VectorInitElem ("isdir", 1, 190, 5)
VectorInitElem ("prototype", 1, 222, 9)
VectorInitElem ("child", 1, 171, 5)
VectorInitElem ("notsock", 1, 213, 7)
VectorInitElem ("): ", 1, 238, 3)
VectorInitElem ("srch", 1, 226, 4)
VectorInitElem ("msgsize", 1, 194, 7)
VectorInitElem ("badf", 1, 168, 4)
VectorInitElem ("output", 1, 253, 6)
VectorInitElem ("Top-level suffix raised exception.\n", 1, 257, 35)
VectorInitElem ("control shouldn\'t reach here", 1, 241, 28)
VectorInitElem ("exist", 1, 179, 5)
VectorInitElem ("MLton.Exit.exit(", 1, 268, 16)
VectorInitElem ("addrinuse", 1, 163, 9)
VectorInitElem ("perm", 1, 219, 4)
VectorInitElem ("acces", 1, 162, 5)
VectorInitElem ("addrnotavail", 1, 164, 12)
VectorInitElem ("Io: ", 1, 262, 4)
VectorInitElem ("Subscript", 1, 250, 9)
VectorInitElem ("nfile", 1, 199, 5)
VectorInitElem ("nametoolong", 1, 195, 11)
VectorInitElem ("Fail: ", 1, 263, 6)
VectorInitElem ("deadlk", 1, 175, 6)
VectorInitElem ("notdir", 1, 211, 6)
VectorInitElem ("fbig", 1, 181, 4)
VectorInitElem ("wouldblock", 1, 231, 10)
VectorInitElem ("Fail8", 1, 259, 5)
VectorInitElem ("timedout", 1, 228, 8)
VectorInitElem ("nodev", 1, 201, 5)
VectorInitElem ("0123456789ABCDEF", 1, 267, 16)
VectorInitElem ("loop", 1, 191, 4)
VectorInitElem ("Fail ", 1, 243, 5)
VectorInitElem ("spipe", 1, 225, 5)
VectorInitElem ("SysErr: ", 1, 266, 8)
VectorInitElem ("xdev", 1, 232, 4)
VectorInitElem ("notsup", 1, 214, 6)
VectorInitElem ("canceled", 1, 170, 8)
VectorInitElem ("notty", 1, 215, 5)
VectorInitElem ("idrm", 1, 183, 4)
VectorInitElem ("Hello, World!\n", 1, 255, 14)
VectorInitElem ("Unknown error", 1, 256, 13)
VectorInitElem ("noprotoopt", 1, 207, 10)
VectorInitElem ("partial write", 1, 235, 13)
VectorInitElem ("notconn", 1, 210, 7)
VectorInitElem ("nomem", 1, 205, 5)
VectorInitElem ("nolck", 1, 204, 5)
VectorInitElem ("nxio", 1, 216, 4)
VectorInitElem ("afnosupport", 1, 165, 11)
VectorInitElem ("intr", 1, 186, 4)
VectorInitElem ("]", 1, 233, 1)
VectorInitElem ("ilseq", 1, 184, 5)
VectorInitElem ("notempty", 1, 212, 8)
VectorInitElem ("already", 1, 167, 7)
VectorInitElem ("inprogress", 1, 185, 10)
VectorInitElem ("MLton.Exit.wrapSuffix", 1, 239, 21)
VectorInitElem ("exit must have 0 <= status < 256", 1, 237, 32)
VectorInitElem ("Top-level handler raised exception.\n", 1, 254, 36)
VectorInitElem ("unhandled exception in Basis Library", 1, 244, 36)
VectorInitElem ("nospc", 1, 208, 5)
VectorInitElem ("netunreach", 1, 198, 10)
VectorInitElem (" [", 1, 265, 2)
VectorInitElem ("opnotsupp", 1, 217, 9)
VectorInitElem ("ClosedStream", 1, 251, 12)
VectorInitElem ("destaddrreq", 1, 176, 11)
VectorInitElem ("connrefused", 1, 173, 11)
VectorInitElem ("fault", 1, 180, 5)
VectorInitElem ("Overflow", 1, 248, 8)
VectorInitElem ("Size", 1, 249, 4)
VectorInitElem ("nomsg", 1, 206, 5)
VectorInitElem ("\n", 1, 240, 1)
VectorInitElem ("protonosupport", 1, 221, 14)
VectorInitElem ("overflow", 1, 218, 8)
VectorInitElem (" \"", 1, 261, 2)
EndVectorInits
static void real_Init() {
}
static uint16_t frameOffsets0[] = {0};
static uint16_t frameOffsets1[] = {1,16};
static uint16_t frameOffsets2[] = {1,24};
static uint16_t frameOffsets3[] = {5,16,24,32,40,48};
static uint16_t frameOffsets4[] = {6,16,24,32,40,48,56};
static uint16_t frameOffsets5[] = {7,16,24,32,40,48,56,64};
static uint16_t frameOffsets6[] = {9,16,24,32,40,48,56,64,72,80};
static uint16_t frameOffsets7[] = {10,16,24,32,40,48,56,64,72,80,96};
static uint16_t frameOffsets8[] = {11,16,24,32,40,48,56,64,72,80,96,104};
static uint16_t frameOffsets9[] = {9,16,32,40,48,56,64,72,80,96};
static uint16_t frameOffsets10[] = {2,16,24};
static uint16_t frameOffsets11[] = {5,48,88,96,104,112};
static uint16_t frameOffsets12[] = {6,16,40,48,88,96,104};
static uint16_t frameOffsets13[] = {3,48,96,104};
static uint16_t frameOffsets14[] = {4,40,48,96,104};
static uint16_t frameOffsets15[] = {3,16,48,96};
static uint16_t frameOffsets16[] = {4,16,24,48,96};
static uint16_t frameOffsets17[] = {2,48,96};
static uint16_t frameOffsets18[] = {4,16,48,96,104};
static uint16_t frameOffsets19[] = {4,40,48,88,96};
static uint16_t frameOffsets20[] = {4,32,48,88,96};
static uint16_t frameOffsets21[] = {6,16,32,48,88,96,104};
static uint16_t frameOffsets22[] = {10,16,24,32,40,48,56,64,72,80,88};
static uint16_t frameOffsets23[] = {1,40};
static uint16_t frameOffsets24[] = {4,16,24,32,40};
static uint16_t frameOffsets25[] = {2,8,16};
static uint16_t frameOffsets26[] = {3,8,16,24};
static uint16_t frameOffsets27[] = {1,0};
static uint16_t frameOffsets28[] = {1,8};
static uint16_t frameOffsets29[] = {2,0,8};
static uint16_t frameOffsets30[] = {3,0,8,16};
static uint16_t frameOffsets31[] = {2,32,40};
static uint16_t frameOffsets32[] = {2,32,64};
static uint16_t frameOffsets33[] = {1,32};
static uint16_t frameOffsets34[] = {2,8,32};
static uint16_t frameOffsets35[] = {3,16,40,56};
static uint16_t frameOffsets36[] = {1,88};
static struct GC_frameLayout frameLayouts[] = {
	{C_FRAME, frameOffsets0, 8},
	{ML_FRAME, frameOffsets0, 8},
	{C_FRAME, frameOffsets1, 32},
	{C_FRAME, frameOffsets2, 40},
	{C_FRAME, frameOffsets0, 24},
	{C_FRAME, frameOffsets3, 64},
	{C_FRAME, frameOffsets4, 72},
	{C_FRAME, frameOffsets5, 80},
	{C_FRAME, frameOffsets6, 96},
	{C_FRAME, frameOffsets7, 112},
	{C_FRAME, frameOffsets8, 120},
	{C_FRAME, frameOffsets9, 112},
	{ML_FRAME, frameOffsets1, 32},
	{ML_FRAME, frameOffsets0, 24},
	{C_FRAME, frameOffsets10, 40},
	{ML_FRAME, frameOffsets11, 128},
	{C_FRAME, frameOffsets12, 120},
	{C_FRAME, frameOffsets13, 120},
	{C_FRAME, frameOffsets14, 120},
	{ML_FRAME, frameOffsets15, 112},
	{C_FRAME, frameOffsets16, 112},
	{ML_FRAME, frameOffsets17, 112},
	{C_FRAME, frameOffsets11, 128},
	{C_FRAME, frameOffsets18, 120},
	{C_FRAME, frameOffsets19, 112},
	{C_FRAME, frameOffsets20, 112},
	{C_FRAME, frameOffsets21, 120},
	{C_FRAME, frameOffsets22, 104},
	{C_FRAME, frameOffsets0, 32},
	{C_FRAME, frameOffsets0, 48},
	{C_FRAME, frameOffsets23, 56},
	{C_FRAME, frameOffsets0, 40},
	{C_FRAME, frameOffsets8, 136},
	{C_FRAME, frameOffsets6, 104},
	{C_FRAME, frameOffsets4, 88},
	{C_FRAME, frameOffsets24, 56},
	{C_FRAME, frameOffsets3, 72},
	{C_FRAME, frameOffsets3, 80},
	{ML_FRAME, frameOffsets25, 32},
	{C_FRAME, frameOffsets26, 40},
	{C_FRAME, frameOffsets27, 16},
	{ML_FRAME, frameOffsets28, 24},
	{C_FRAME, frameOffsets25, 32},
	{C_FRAME, frameOffsets28, 24},
	{C_FRAME, frameOffsets29, 24},
	{C_FRAME, frameOffsets25, 40},
	{C_FRAME, frameOffsets1, 40},
	{C_FRAME, frameOffsets30, 32},
	{C_FRAME, frameOffsets31, 72},
	{ML_FRAME, frameOffsets0, 40},
	{C_FRAME, frameOffsets32, 80},
	{C_FRAME, frameOffsets33, 48},
	{ML_FRAME, frameOffsets34, 48},
	{C_FRAME, frameOffsets34, 48},
	{C_FRAME, frameOffsets28, 40},
	{C_FRAME, frameOffsets35, 72},
	{C_FRAME, frameOffsets0, 80},
	{C_FRAME, frameOffsets0, 96},
	{C_FRAME, frameOffsets36, 104},
	{C_FRAME, frameOffsets0, 88},
	{C_FRAME, frameOffsets0, 16},
};
static struct GC_objectType objectTypes[] = {
	{ STACK_TAG, FALSE, 0, 0 },
	{ NORMAL_TAG, TRUE, 16, 1 },
	{ WEAK_TAG, FALSE, 16, 0 },
	{ ARRAY_TAG, FALSE, 1, 0 },
	{ ARRAY_TAG, FALSE, 4, 0 },
	{ ARRAY_TAG, FALSE, 2, 0 },
	{ ARRAY_TAG, FALSE, 8, 0 },
	{ NORMAL_TAG, TRUE, 0, 1 },
	{ NORMAL_TAG, FALSE, 16, 0 },
	{ NORMAL_TAG, FALSE, 8, 1 },
	{ NORMAL_TAG, TRUE, 8, 0 },
	{ ARRAY_TAG, TRUE, 1, 0 },
	{ NORMAL_TAG, TRUE, 8, 0 },
	{ NORMAL_TAG, TRUE, 8, 0 },
	{ NORMAL_TAG, FALSE, 0, 2 },
	{ NORMAL_TAG, FALSE, 0, 3 },
	{ NORMAL_TAG, TRUE, 0, 1 },
	{ NORMAL_TAG, TRUE, 8, 0 },
	{ NORMAL_TAG, FALSE, 0, 4 },
	{ NORMAL_TAG, FALSE, 8, 1 },
	{ NORMAL_TAG, TRUE, 0, 1 },
	{ NORMAL_TAG, FALSE, 16, 0 },
	{ ARRAY_TAG, TRUE, 8, 0 },
	{ NORMAL_TAG, TRUE, 0, 1 },
	{ NORMAL_TAG, TRUE, 0, 1 },
	{ NORMAL_TAG, FALSE, 0, 4 },
	{ NORMAL_TAG, FALSE, 0, 2 },
	{ NORMAL_TAG, FALSE, 0, 1 },
	{ NORMAL_TAG, FALSE, 0, 1 },
	{ NORMAL_TAG, FALSE, 8, 1 },
	{ NORMAL_TAG, FALSE, 0, 3 },
	{ NORMAL_TAG, FALSE, 0, 2 },
	{ NORMAL_TAG, FALSE, 0, 2 },
	{ NORMAL_TAG, FALSE, 0, 2 },
	{ NORMAL_TAG, FALSE, 0, 2 },
	{ NORMAL_TAG, FALSE, 0, 2 },
	{ NORMAL_TAG, FALSE, 0, 2 },
	{ NORMAL_TAG, FALSE, 0, 2 },
	{ NORMAL_TAG, FALSE, 0, 2 },
	{ NORMAL_TAG, FALSE, 0, 2 },
	{ NORMAL_TAG, FALSE, 0, 2 },
};
static uint32_t* sourceSeqs[] = {
};
static GC_sourceSeqIndex frameSources[] = {
};
static struct GC_sourceLabel sourceLabels[] = {
};
static char* sourceNames[] = {
};
static struct GC_source sources[] = {
};
static char* atMLtons[] = {
	"16",
	"@MLton",
	"--",
};
PRIVATE CPointer localCPointer[158];
PRIVATE Int8 localInt8[0];
PRIVATE Int16 localInt16[0];
PRIVATE Int32 localInt32[0];
PRIVATE Int64 localInt64[0];
PRIVATE Objptr localObjptr[8];
PRIVATE Real32 localReal32[0];
PRIVATE Real64 localReal64[0];
PRIVATE Word8 localWord8[3];
PRIVATE Word16 localWord16[0];
PRIVATE Word32 localWord32[5];
PRIVATE Word64 localWord64[11];
MLtonMain (8, 0x833C516A, 144, TRUE, PROFILE_NONE, FALSE, F_0)
int main (int argc, char* argv[]) {
return (MLton_main (argc, argv));
}
